/**
 * @file    test_crc.c
 * @brief   Unit tests for the AUTOSAR Crc Library.
 *
 * Expected values come from test/support/Crc_TestVectors.h, which is generated by
 * tools/crc_reference.py -- an independent bit-at-a-time model that first proves
 * itself against each profile's published check constant. The C code is therefore
 * never compared against itself.
 *
 * @req SWREQ-INT-0010, SWREQ-INT-0011, SWREQ-INT-0012
 * @verifies TS-CRC-001 .. TS-CRC-009
 *
 * @copyright
 * Copyright (c) 2024-2026 Abdullah Shabbir. All rights reserved.
 * SPDX-License-Identifier: Proprietary
 */

#include "services/Crc/Crc.h"
#include "Crc_TestVectors.h"
#include "unity.h"

void setUp(void) {}
void tearDown(void) {}

/*==================================================================================================
 *  TS-CRC-001 .. 006 : every profile reproduces every generated vector
 *================================================================================================*/

/** @test TS-CRC-001 CRC-8 (SAE J1850) matches the reference model on all vectors. */
static void test_Crc8_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint8 actual = Crc_CalculateCRC8(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX8_MESSAGE(v->expCrc8, actual, v->name);
    }
}

/** @test TS-CRC-002 CRC-8/H2F matches the reference model on all vectors. */
static void test_Crc8H2F_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint8 actual = Crc_CalculateCRC8H2F(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX8_MESSAGE(v->expCrc8H2F, actual, v->name);
    }
}

/** @test TS-CRC-003 CRC-16/CCITT-FALSE matches the reference model on all vectors. */
static void test_Crc16_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint16 actual = Crc_CalculateCRC16(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX16_MESSAGE(v->expCrc16, actual, v->name);
    }
}

/** @test TS-CRC-004 CRC-16/ARC matches the reference model on all vectors. */
static void test_Crc16Arc_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint16 actual = Crc_CalculateCRC16ARC(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX16_MESSAGE(v->expCrc16Arc, actual, v->name);
    }
}

/** @test TS-CRC-005 CRC-32 (IEEE 802.3) matches the reference model on all vectors. */
static void test_Crc32_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint32 actual = Crc_CalculateCRC32(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX32_MESSAGE(v->expCrc32, actual, v->name);
    }
}

/** @test TS-CRC-006 CRC-32/P4 matches the reference model on all vectors. */
static void test_Crc32P4_MatchesReferenceVectors(void)
{
    uint32 i;
    for (i = 0u; i < CRC_TEST_VECTOR_COUNT; i++)
    {
        const Crc_TestVectorType *v = &Crc_TestVectors[i];
        const uint32 actual = Crc_CalculateCRC32P4(v->data, v->length, 0u, TRUE);
        TEST_ASSERT_EQUAL_HEX32_MESSAGE(v->expCrc32P4, actual, v->name);
    }
}

/*==================================================================================================
 *  TS-CRC-007 : streaming equals one-shot
 *
 *  FsAbs and Ota rely on this: they checksum megabytes through a small stack
 *  buffer. If the continuation contract were wrong, every record would still get a
 *  self-consistent CRC and the fault would only surface when a different tool
 *  verified the file.
 *================================================================================================*/

/** @test TS-CRC-007 Splitting a payload at every offset yields the one-shot CRC. */
static void test_AllProfiles_StreamingEqualsOneShot(void)
{
    /* The 255-byte vector is the only one long enough to split meaningfully. */
    const Crc_TestVectorType *v = &Crc_TestVectors[CRC_TEST_VECTOR_COUNT - 1u];
    uint32 split;

    TEST_ASSERT_EQUAL_UINT32_MESSAGE(255u, v->length, "expected the 255-byte vector last");

    for (split = 0u; split <= v->length; split++)
    {
        const uint32 tailLen = v->length - split;

        const uint8 c8 = Crc_CalculateCRC8(&v->data[split], tailLen,
                                           Crc_CalculateCRC8(v->data, split, 0u, TRUE), FALSE);
        const uint8 c8h = Crc_CalculateCRC8H2F(
            &v->data[split], tailLen, Crc_CalculateCRC8H2F(v->data, split, 0u, TRUE), FALSE);
        const uint16 c16 = Crc_CalculateCRC16(&v->data[split], tailLen,
                                              Crc_CalculateCRC16(v->data, split, 0u, TRUE), FALSE);
        const uint16 c16a = Crc_CalculateCRC16ARC(
            &v->data[split], tailLen, Crc_CalculateCRC16ARC(v->data, split, 0u, TRUE), FALSE);
        const uint32 c32 = Crc_CalculateCRC32(&v->data[split], tailLen,
                                              Crc_CalculateCRC32(v->data, split, 0u, TRUE), FALSE);
        const uint32 c32p = Crc_CalculateCRC32P4(
            &v->data[split], tailLen, Crc_CalculateCRC32P4(v->data, split, 0u, TRUE), FALSE);

        TEST_ASSERT_EQUAL_HEX8(v->expCrc8, c8);
        TEST_ASSERT_EQUAL_HEX8(v->expCrc8H2F, c8h);
        TEST_ASSERT_EQUAL_HEX16(v->expCrc16, c16);
        TEST_ASSERT_EQUAL_HEX16(v->expCrc16Arc, c16a);
        TEST_ASSERT_EQUAL_HEX32(v->expCrc32, c32);
        TEST_ASSERT_EQUAL_HEX32(v->expCrc32P4, c32p);
    }
}

/*==================================================================================================
 *  TS-CRC-008 : defensive behaviour
 *================================================================================================*/

/** @test TS-CRC-008 A zero-length buffer returns the profile's initial value. */
static void test_ZeroLength_ReturnsInitialValue(void)
{
    const uint8 dummy = 0x5Au;

    /* CRC-16/CCITT-FALSE has no final XOR, so an empty payload yields the init value
     * directly. This is the documented value a zero-length RS485 frame must produce. */
    TEST_ASSERT_EQUAL_HEX16(CRC16_EMPTY_RESULT, Crc_CalculateCRC16(&dummy, 0u, 0u, TRUE));

    /* The CRC-8 and CRC-32 profiles do apply a final XOR, so an empty payload
     * returns init ^ xorout, which is zero for both. */
    TEST_ASSERT_EQUAL_HEX8(0x00u, Crc_CalculateCRC8(&dummy, 0u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX8(0x00u, Crc_CalculateCRC8H2F(&dummy, 0u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX16(0x0000u, Crc_CalculateCRC16ARC(&dummy, 0u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX32(0x00000000uL, Crc_CalculateCRC32(&dummy, 0u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX32(0x00000000uL, Crc_CalculateCRC32P4(&dummy, 0u, 0u, TRUE));
}

/** @test TS-CRC-008b A NULL buffer with a non-zero length never looks like success. */
static void test_NullPointerWithLength_ReturnsInitialValue(void)
{
    /* The contract is "return a value no real payload produces" rather than "return
     * 0", because 0 is a perfectly reachable CRC and would be indistinguishable
     * from a genuine result at the call site. */
    TEST_ASSERT_EQUAL_HEX8(CRC8_INITIAL_VALUE, Crc_CalculateCRC8(NULL_PTR, 4u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX8(CRC8H2F_INITIAL_VALUE, Crc_CalculateCRC8H2F(NULL_PTR, 4u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX16(CRC16_INITIAL_VALUE, Crc_CalculateCRC16(NULL_PTR, 4u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX16(CRC16ARC_INITIAL_VALUE, Crc_CalculateCRC16ARC(NULL_PTR, 4u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX32(CRC32_INITIAL_VALUE, Crc_CalculateCRC32(NULL_PTR, 4u, 0u, TRUE));
    TEST_ASSERT_EQUAL_HEX32(CRC32P4_INITIAL_VALUE, Crc_CalculateCRC32P4(NULL_PTR, 4u, 0u, TRUE));

    /* A NULL pointer with length 0 is legal and must behave like an empty buffer. */
    TEST_ASSERT_EQUAL_HEX16(CRC16_EMPTY_RESULT, Crc_CalculateCRC16(NULL_PTR, 0u, 0u, TRUE));
}

/*==================================================================================================
 *  TS-CRC-009 : error-detection strength
 *================================================================================================*/

/** @test TS-CRC-009 Every single-bit error in a 53-byte frame is detected by CRC-16. */
static void test_Crc16_DetectsEverySingleBitError(void)
{
    /* 53 bytes is the length of the BATT0100 battery-parameter response, the frame
     * this CRC actually guards on the RS485 bus. */
    uint8 frame[53];
    uint16 i;
    uint16 reference;

    for (i = 0u; i < (uint16)sizeof(frame); i++)
    {
        frame[i] = (uint8)(i * 7u);
    }
    reference = Crc_CalculateCRC16(frame, (uint32)sizeof(frame), 0u, TRUE);

    for (i = 0u; i < (uint16)(sizeof(frame) * 8u); i++)
    {
        const uint16 byteIdx = i / 8u;
        const uint8 bitMask = (uint8)(1u << (i % 8u));
        uint16 corrupted;

        frame[byteIdx] ^= bitMask;
        corrupted = Crc_CalculateCRC16(frame, (uint32)sizeof(frame), 0u, TRUE);
        frame[byteIdx] ^= bitMask; /* restore */

        TEST_ASSERT_NOT_EQUAL_MESSAGE(reference, corrupted, "single-bit error went undetected");
    }
}

/** @test TS-CRC-009b CRC-32 detects a byte-order swap that a checksum would miss. */
static void test_Crc32_DetectsTransposition(void)
{
    const uint8 original[4] = {0x11u, 0x22u, 0x33u, 0x44u};
    const uint8 swapped[4] = {0x22u, 0x11u, 0x33u, 0x44u};

    TEST_ASSERT_NOT_EQUAL(Crc_CalculateCRC32(original, 4u, 0u, TRUE),
                          Crc_CalculateCRC32(swapped, 4u, 0u, TRUE));
}

/*==================================================================================================
 *  TS-CRC-010 : version information
 *================================================================================================*/

/** @test TS-CRC-010 GetVersionInfo fills the struct and tolerates NULL. */
static void test_GetVersionInfo(void)
{
    Std_VersionInfoType info;

    info.vendorID = 0u;
    info.moduleID = 0u;
    Crc_GetVersionInfo(&info);

    TEST_ASSERT_EQUAL_HEX16(CRC_VENDOR_ID, info.vendorID);
    TEST_ASSERT_EQUAL_HEX16(MODULE_ID_CRC, info.moduleID);
    TEST_ASSERT_EQUAL_UINT8(CRC_SW_MAJOR_VERSION, info.sw_major_version);

    Crc_GetVersionInfo(NULL_PTR); /* must not trap */
}

/*==================================================================================================
 *  Runner
 *================================================================================================*/

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_Crc8_MatchesReferenceVectors);
    RUN_TEST(test_Crc8H2F_MatchesReferenceVectors);
    RUN_TEST(test_Crc16_MatchesReferenceVectors);
    RUN_TEST(test_Crc16Arc_MatchesReferenceVectors);
    RUN_TEST(test_Crc32_MatchesReferenceVectors);
    RUN_TEST(test_Crc32P4_MatchesReferenceVectors);
    RUN_TEST(test_AllProfiles_StreamingEqualsOneShot);
    RUN_TEST(test_ZeroLength_ReturnsInitialValue);
    RUN_TEST(test_NullPointerWithLength_ReturnsInitialValue);
    RUN_TEST(test_Crc16_DetectsEverySingleBitError);
    RUN_TEST(test_Crc32_DetectsTransposition);
    RUN_TEST(test_GetVersionInfo);
    return UNITY_END();
}
