/**
 * @file    test_rs485.c
 * @brief   Unit tests for the RS485 battery-pack protocol handler.
 *
 * Expected frames come from test/support/Rs485_TestVectors.h, generated by
 * tools/rs485_reference.py. That generator reproduces the CRC of two response frames taken
 * verbatim from the v1 firmware, which cross-validates the frame layout and CRC parameters
 * against code that was demonstrably talking to real packs.
 *
 * Several cases here exist specifically to pin defects found in v1; each says which.
 *
 * @req SWREQ-BAT-0001 .. SWREQ-BAT-0020
 * @verifies TS-RS485-001 .. TS-RS485-022
 *
 * @copyright
 * Copyright (c) 2024-2026 Abdullah Shabbir. All rights reserved.
 * SPDX-License-Identifier: Proprietary
 */

#include <string.h>

#include "services/Crc/Crc.h"
#include "services/Det/Det.h"
#include "mcal/Dio/Dio.h"
#include "mcal/Gpt/Gpt.h"
#include "ecuabs/Rs485If/Rs485If.h"
#include "Rs485_TestVectors.h"
#include "Stub_Mcal.h"
#include "mcal/Uart/Uart.h"
#include "unity.h"

/** The battery bus is UART instance 0; the stub models the same numbering. */
#define RS485_BUS ((uint8)UART_INSTANCE_RS485)

void setUp(void)
{
    Stub_Mcal_ResetAll();
    Det_Init();
    Rs485If_DeInit();
}

void tearDown(void)
{
    Rs485If_DeInit();
}

/*==================================================================================================
 *  TS-RS485-001 .. 005 : frame construction
 *================================================================================================*/

/** @test TS-RS485-001 A no-payload request matches the reference frame byte for byte. */
static void test_BuildRequest_MatchesReferenceFrame(void)
{
    uint8 frame[RS485IF_REQUEST_FRAME_SIZE];

    TEST_ASSERT_EQUAL(
        E_OK, Rs485If_BuildRequest(frame, (uint8)sizeof(frame), RS485_TV_SERIAL, RS485IF_CMD_SERIAL_NUMBER));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestSerial, frame, sizeof(frame));

    TEST_ASSERT_EQUAL(
        E_OK, Rs485If_BuildRequest(frame, (uint8)sizeof(frame), RS485_TV_SERIAL, RS485IF_CMD_BATTERY_PARAMS));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestBattery, frame, sizeof(frame));

    TEST_ASSERT_EQUAL(
        E_OK, Rs485If_BuildRequest(frame, (uint8)sizeof(frame), RS485_TV_SERIAL, RS485IF_CMD_CELL_PARAMS));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestCells, frame, sizeof(frame));
}

/** @test TS-RS485-002 A two-byte-payload request matches the reference frame. */
static void test_BuildRequestExt_MatchesReferenceFrame(void)
{
    uint8 frame[RS485IF_REQUEST_FRAME_SIZE_EXT];

    TEST_ASSERT_EQUAL(E_OK, Rs485If_BuildRequestExt(frame, (uint8)sizeof(frame), 0u,
                                                    RS485IF_CMD_BATTERY_PARAMS, 0x00u, 0x0Fu));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestSwitchAll, frame, sizeof(frame));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_BuildRequestExt(frame, (uint8)sizeof(frame), 0u,
                                                    RS485IF_CMD_BATTERY_PARAMS, 0x00u, 0x00u));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestSwitchNone, frame, sizeof(frame));
}

/**
 * @test TS-RS485-003 Frame construction writes nothing past the end of its buffer.
 *
 * This is the v1 stack buffer overflow, pinned. v1's @c switchOnOffBatteries declared a
 * fifteen-byte array, called @c appendCRC16(pkt, 15) -- writing indices 15 and 16 -- and
 * then transmitted seventeen bytes from it. The guard bytes below occupy exactly those
 * indices; if the builder writes there, they change.
 */
static void test_BuildRequest_DoesNotOverflowBuffer(void)
{
    /* One struct so the layout is fixed and the guard genuinely sits immediately after the
     * frame, rather than wherever the compiler happens to place a separate array. */
    struct
    {
        uint8 frame[RS485IF_REQUEST_FRAME_SIZE_EXT];
        uint8 guard[8];
    } buffer;

    (void)memset(&buffer, 0xA5, sizeof(buffer));

    /* Build the short frame into a buffer sized for the long one: indices 15 and 16 must be
     * left alone, because a 15-byte frame ends at index 14. */
    TEST_ASSERT_EQUAL(E_OK, Rs485If_BuildRequest(buffer.frame, RS485IF_REQUEST_FRAME_SIZE, RS485_TV_SERIAL,
                                                 RS485IF_CMD_SERIAL_NUMBER));
    TEST_ASSERT_EQUAL_HEX8_MESSAGE(0xA5u, buffer.frame[15],
                                   "BuildRequest wrote past its declared frame length");
    TEST_ASSERT_EQUAL_HEX8_MESSAGE(0xA5u, buffer.frame[16],
                                   "BuildRequest wrote past its declared frame length");

    /* Now the long frame, which legitimately uses all 17 bytes. The guard beyond it must
     * still be untouched -- that is the byte v1 corrupted. */
    (void)memset(&buffer, 0xA5, sizeof(buffer));
    TEST_ASSERT_EQUAL(E_OK, Rs485If_BuildRequestExt(buffer.frame, RS485IF_REQUEST_FRAME_SIZE_EXT, 0u,
                                                    RS485IF_CMD_BATTERY_PARAMS, 0x00u, 0x0Fu));
    {
        uint8 i;
        for (i = 0u; i < (uint8)sizeof(buffer.guard); i++)
        {
            TEST_ASSERT_EQUAL_HEX8_MESSAGE(0xA5u, buffer.guard[i], "BuildRequestExt overflowed its buffer");
        }
    }
}

/**
 * @test TS-RS485-004 A buffer too small for the frame is refused, not truncated.
 *
 * The structural fix for the v1 overflow: the builder is told the capacity and rejects a
 * request it cannot satisfy, instead of writing the CRC wherever the arithmetic lands.
 */
static void test_BuildRequest_RejectsUndersizedBuffer(void)
{
    uint8 tooSmall[RS485IF_REQUEST_FRAME_SIZE - 1u];
    uint8 extTooSmall[RS485IF_REQUEST_FRAME_SIZE_EXT - 1u];
    Det_StatisticsType stats;

    (void)memset(tooSmall, 0x5Au, sizeof(tooSmall));
    (void)memset(extTooSmall, 0x5Au, sizeof(extTooSmall));

    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_BuildRequest(tooSmall, (uint8)sizeof(tooSmall), RS485_TV_SERIAL,
                                                     RS485IF_CMD_SERIAL_NUMBER));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_BuildRequestExt(extTooSmall, (uint8)sizeof(extTooSmall), 0u,
                                                        RS485IF_CMD_BATTERY_PARAMS, 0u, 0u));

    /* Nothing may have been written before the size was checked. */
    TEST_ASSERT_EACH_EQUAL_HEX8(0x5Au, tooSmall, sizeof(tooSmall));
    TEST_ASSERT_EACH_EQUAL_HEX8(0x5Au, extTooSmall, sizeof(extTooSmall));

    /* And the rejection is recorded: an undersized buffer is a caller defect. */
    Det_GetStatistics(&stats);
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32(2u, stats.devErrorCount);
}

/** @test TS-RS485-005 A NULL destination is rejected. */
static void test_BuildRequest_RejectsNullBuffer(void)
{
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_BuildRequest(NULL_PTR, RS485IF_REQUEST_FRAME_SIZE, 0u, 0u));
    TEST_ASSERT_EQUAL(E_NOT_OK,
                      Rs485If_BuildRequestExt(NULL_PTR, RS485IF_REQUEST_FRAME_SIZE_EXT, 0u, 0u, 0u, 0u));
}

/*==================================================================================================
 *  TS-RS485-006 .. 011 : response validation
 *================================================================================================*/

/** @test TS-RS485-006 A well-formed response is accepted. */
static void test_ValidateResponse_AcceptsGoldenFrames(void)
{
    TEST_ASSERT_EQUAL(E_OK, Rs485If_ValidateResponse(Rs485_Tv_ResponseSerial, RS485IF_SERIAL_RESPONSE_SIZE,
                                                     RS485IF_SERIAL_RESPONSE_SIZE));
    TEST_ASSERT_EQUAL(E_OK, Rs485If_ValidateResponse(Rs485_Tv_ResponseCellsV1, RS485IF_CELL_RESPONSE_SIZE,
                                                     RS485IF_CELL_RESPONSE_SIZE));
    TEST_ASSERT_EQUAL(E_OK,
                      Rs485If_ValidateResponse(Rs485_Tv_ResponseBatteryNominal, RS485IF_BATTERY_RESPONSE_SIZE,
                                               RS485IF_BATTERY_RESPONSE_SIZE));
}

/**
 * @test TS-RS485-007 The v1 fixture with its wrong CRC is rejected.
 *
 * A real-world bad frame rather than a synthetic one. v1 never noticed, because its
 * @c readResponse returned true unconditionally on the simulation path -- before reaching
 * its own CRC check -- so simulation mode validated nothing at all.
 */
static void test_ValidateResponse_RejectsV1CorruptFrame(void)
{
    Rs485If_StatisticsType stats;

    TEST_ASSERT_EQUAL(E_CRC_FAIL,
                      Rs485If_ValidateResponse(Rs485_Tv_ResponseBatteryV1Corrupt,
                                               RS485IF_BATTERY_RESPONSE_SIZE, RS485IF_BATTERY_RESPONSE_SIZE));

    /* Confirm the fixture really is the v1 one, and that its correct CRC differs. */
    TEST_ASSERT_NOT_EQUAL(RS485_TV_V1_BATT_CORRECT_CRC, RS485_TV_V1_BATT_EMBEDDED_CRC);

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(1u, stats.crcFailures);
}

/** @test TS-RS485-008 Every single-bit corruption of a response is detected. */
static void test_ValidateResponse_DetectsEverySingleBitError(void)
{
    uint8 frame[RS485IF_BATTERY_RESPONSE_SIZE];
    uint16 bit;

    (void)memcpy(frame, Rs485_Tv_ResponseBatteryNominal, sizeof(frame));
    TEST_ASSERT_EQUAL(E_OK,
                      Rs485If_ValidateResponse(frame, (uint8)sizeof(frame), RS485IF_BATTERY_RESPONSE_SIZE));

    for (bit = 0u; bit < (uint16)(sizeof(frame) * 8u); bit++)
    {
        const uint16 byteIdx = bit / 8u;
        const uint8 mask = (uint8)(1u << (bit % 8u));

        frame[byteIdx] ^= mask;
        TEST_ASSERT_NOT_EQUAL_MESSAGE(
            E_OK, Rs485If_ValidateResponse(frame, (uint8)sizeof(frame), RS485IF_BATTERY_RESPONSE_SIZE),
            "a single-bit corruption was accepted");
        frame[byteIdx] ^= mask;
    }
}

/**
 * @test TS-RS485-009 A wrong start or direction byte is a header error, not a CRC error.
 *
 * The distinction is what keeps the CRC-failure rate usable as a measure of harness
 * quality: a foreign device's well-formed frame must not inflate it.
 */
static void test_ValidateResponse_ClassifiesHeaderErrorsSeparately(void)
{
    uint8 frame[RS485IF_BATTERY_RESPONSE_SIZE];
    Rs485If_StatisticsType stats;

    (void)memcpy(frame, Rs485_Tv_ResponseBatteryNominal, sizeof(frame));
    frame[0] = 0xFEu; /* wrong start byte */
    TEST_ASSERT_EQUAL(E_NOT_OK,
                      Rs485If_ValidateResponse(frame, (uint8)sizeof(frame), RS485IF_BATTERY_RESPONSE_SIZE));

    (void)memcpy(frame, Rs485_Tv_ResponseBatteryNominal, sizeof(frame));
    frame[1] = RS485IF_DIR_REQUEST; /* our own echo, not a reply */
    TEST_ASSERT_EQUAL(E_NOT_OK,
                      Rs485If_ValidateResponse(frame, (uint8)sizeof(frame), RS485IF_BATTERY_RESPONSE_SIZE));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(2u, stats.headerFailures);
    TEST_ASSERT_EQUAL_UINT32(0u, stats.crcFailures);
}

/** @test TS-RS485-010 A declared length that disagrees with the frame type is rejected. */
static void test_ValidateResponse_RejectsWrongDeclaredLength(void)
{
    uint8 frame[RS485IF_BATTERY_RESPONSE_SIZE];

    (void)memcpy(frame, Rs485_Tv_ResponseBatteryNominal, sizeof(frame));

    /* Claim a cell-response length in a pack-response frame, and repair the CRC so that
     * only the length field is wrong. A validator that checked the CRC alone would accept
     * this and then decode 66 bytes of payload out of a 38-byte frame. */
    frame[2] = (uint8)(RS485IF_CELL_RESPONSE_SIZE >> 8u);
    frame[3] = (uint8)(RS485IF_CELL_RESPONSE_SIZE & 0xFFu);
    {
        const uint16 crc = Crc_CalculateCRC16(frame, sizeof(frame) - 2u, 0u, TRUE);
        frame[sizeof(frame) - 2u] = (uint8)(crc >> 8u);
        frame[sizeof(frame) - 1u] = (uint8)(crc & 0xFFu);
    }

    TEST_ASSERT_EQUAL(E_INVALID_PARAM,
                      Rs485If_ValidateResponse(frame, (uint8)sizeof(frame), RS485IF_BATTERY_RESPONSE_SIZE));
}

/** @test TS-RS485-011 A truncated frame is rejected as short, before any field is read. */
static void test_ValidateResponse_RejectsShortFrame(void)
{
    Rs485If_StatisticsType stats;

    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ValidateResponse(Rs485_Tv_ResponseBatteryNominal,
                                                         RS485IF_BATTERY_RESPONSE_SIZE - 1u,
                                                         RS485IF_BATTERY_RESPONSE_SIZE));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(1u, stats.shortFrames);

    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ValidateResponse(NULL_PTR, 53u, 53u));
}

/*==================================================================================================
 *  TS-RS485-012 .. 016 : payload decoding
 *================================================================================================*/

/** @test TS-RS485-012 A nominal pack response decodes to the expected field values. */
static void test_ParsePackData_DecodesNominalFrame(void)
{
    Rs485If_PackDataType data;

    TEST_ASSERT_EQUAL(E_OK, Rs485If_ParsePackData(Rs485_Tv_ResponseBatteryNominal, &data));

    TEST_ASSERT_EQUAL_UINT16(RS485_TV_NOM_VOLTAGE, data.voltage);
    TEST_ASSERT_EQUAL_UINT16(RS485_TV_NOM_VOLTAGE_HIGH, data.voltageHighest);
    TEST_ASSERT_EQUAL_UINT16(RS485_TV_NOM_VOLTAGE_LOW, data.voltageLowest);
    TEST_ASSERT_EQUAL_INT32(RS485_TV_NOM_CURRENT, data.current);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NOM_TEMP, data.temperature);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NOM_TEMP_HIGH, data.temperatureHigh);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NOM_TEMP_LOW, data.temperatureLow);
    TEST_ASSERT_EQUAL_UINT8(RS485_TV_NOM_SOC, data.stateOfCharge);
    TEST_ASSERT_EQUAL_UINT8(RS485_TV_NOM_SOH, data.stateOfHealth);
    TEST_ASSERT_EQUAL_UINT32(RS485_TV_NOM_CHARGE_WH, data.chargeEnergyWh);
    TEST_ASSERT_EQUAL_UINT32(RS485_TV_NOM_DISCHARGE_WH, data.dischargeEnergyWh);
    TEST_ASSERT_EQUAL_UINT32(RS485_TV_NOM_CHARGE_SEC, data.chargeTimeSec);
    TEST_ASSERT_EQUAL_UINT32(RS485_TV_NOM_DISCHARGE_SEC, data.dischargeTimeSec);
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_NOM_FLAGS, data.statusFlags);
}

/**
 * @test TS-RS485-013 Negative current and sub-zero temperatures decode correctly.
 *
 * The v1 decoder bug, pinned. It wrote
 * @c (int32_t)(buffer[n] << 24) | (buffer[n+1] << 16) | ..., where the cast applies only to
 * the first term and @c buffer[n] << 24 is undefined once the top bit is set. A discharging
 * pack -- negative current, the normal driving condition -- is exactly the case that
 * exercises it.
 */
static void test_ParsePackData_DecodesNegativeFields(void)
{
    Rs485If_PackDataType data;

    TEST_ASSERT_EQUAL(E_OK, Rs485If_ParsePackData(Rs485_Tv_ResponseBatteryNegative, &data));

    TEST_ASSERT_EQUAL_INT32(RS485_TV_NEG_CURRENT, data.current);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NEG_TEMP, data.temperature);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NEG_TEMP_HIGH, data.temperatureHigh);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_NEG_TEMP_LOW, data.temperatureLow);
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_NEG_FLAGS, data.statusFlags);

    /* A negative current must not read back as a huge positive value, which is the visible
     * symptom of the misplaced cast. */
    TEST_ASSERT_TRUE(data.current < 0);
}

/** @test TS-RS485-014 Saturated fields decode at their representable limits. */
static void test_ParsePackData_DecodesExtremes(void)
{
    Rs485If_PackDataType data;

    TEST_ASSERT_EQUAL(E_OK, Rs485If_ParsePackData(Rs485_Tv_ResponseBatteryExtremes, &data));

    TEST_ASSERT_EQUAL_UINT16(0xFFFFu, data.voltage);
    TEST_ASSERT_EQUAL_INT32(RS485_TV_EXT_CURRENT, data.current);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_EXT_TEMP, data.temperature);
    TEST_ASSERT_EQUAL_INT16(RS485_TV_EXT_TEMP_HIGH, data.temperatureHigh);
    TEST_ASSERT_EQUAL_UINT32(0xFFFFFFFFuL, data.statusFlags);
}

/** @test TS-RS485-015 A cell response decodes all 23 cells and 4 sensors in order. */
static void test_ParseCellData_DecodesAllChannels(void)
{
    Rs485If_CellDataType data;
    uint8 i;

    TEST_ASSERT_EQUAL(E_OK, Rs485If_ParseCellData(Rs485_Tv_ResponseCellsNominal, &data));

    /* A monotonically increasing ramp, so a transposed pair of cells is visible rather
     * than hidden behind identical values. */
    for (i = 0u; i < RS485IF_CELLS_PER_PACK; i++)
    {
        const uint16 expected = (uint16)(RS485_TV_CELL_BASE_MV + ((uint16)i * RS485_TV_CELL_STEP_MV));
        TEST_ASSERT_EQUAL_UINT16(expected, data.cellVoltage[i]);
    }

    TEST_ASSERT_EQUAL_INT32(RS485_TV_CELL_CURRENT, data.current);
    for (i = 0u; i < RS485IF_TEMPS_PER_PACK; i++)
    {
        const sint16 expected = (sint16)(RS485_TV_CELL_TEMP_BASE + ((sint16)i * RS485_TV_CELL_TEMP_STEP));
        TEST_ASSERT_EQUAL_INT16(expected, data.temperature[i]);
    }
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_CELL_FLAGS1, data.statusFlags1);
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_CELL_FLAGS2, data.statusFlags2);
}

/** @test TS-RS485-016 The serial number echoed in a response is read correctly. */
static void test_ParseSerialNumber(void)
{
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_SERIAL, Rs485If_ParseSerialNumber(Rs485_Tv_ResponseSerial));
    TEST_ASSERT_EQUAL_HEX32(0u, Rs485If_ParseSerialNumber(NULL_PTR));
}

/** @test TS-RS485-016b Decoders reject NULL arguments. */
static void test_Parsers_RejectNull(void)
{
    Rs485If_PackDataType pack;
    Rs485If_CellDataType cells;

    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ParsePackData(NULL_PTR, &pack));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ParsePackData(Rs485_Tv_ResponseBatteryNominal, NULL_PTR));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ParseCellData(NULL_PTR, &cells));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ParseCellData(Rs485_Tv_ResponseCellsNominal, NULL_PTR));
}

/*==================================================================================================
 *  TS-RS485-017 .. 022 : bus transactions
 *================================================================================================*/

/**
 * @test TS-RS485-017 An exchange purges stale receive data before transmitting.
 *
 * The v1 defect: it called @c flush(), which drains the transmit buffer and leaves received
 * bytes in place, so a late reply from the previous pack was parsed as the current one's.
 */
static void test_Exchange_PurgesStaleReceiveDataFirst(void)
{
    Rs485If_StatisticsType stats;
    const uint8 junk[5] = {0xDEu, 0xADu, 0xBEu, 0xEFu, 0x00u};

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    /* Leave debris in the receive buffer, then a well-formed switch acknowledgement. */
    Stub_Uart_QueueRxBytes(RS485_BUS, junk, (uint16)sizeof(junk));
    Stub_Uart_QueueRxBytes(RS485_BUS, Rs485_Tv_RequestSwitchAll, RS485IF_REQUEST_FRAME_SIZE_EXT);

    /* The acknowledgement echoes a request-direction frame, so validation rejects it -- but
     * the purge must still have happened and been counted. */
    STD_DISCARD(Rs485If_SwitchPacks(0x00u, 0x0Fu));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32((uint32)sizeof(junk) + RS485IF_REQUEST_FRAME_SIZE_EXT, stats.staleRxBytes);
}

/**
 * @test TS-RS485-018 The driver-enable line is asserted to transmit and released to receive.
 *
 * On a half-duplex bus a driver left enabled blocks every other device, so the resting
 * state must be receive and the assertion must be strictly bracketed around the transmit.
 */
static void test_Exchange_TogglesDriverEnableAroundTransmit(void)
{
    TEST_ASSERT_EQUAL(E_OK, Uart_Init());

    /* Init alone must leave the transceiver receiving. */
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());
    TEST_ASSERT_EQUAL_HEX8(STD_LOW, Stub_Dio_GetLevel(DIO_CHANNEL_RS485_DE));

    STD_DISCARD(Rs485If_SwitchPacks(0x00u, 0x0Fu));

    /* Asserted then released: at least one high and one low transition. */
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32(2u, Stub_Dio_GetToggleCount(DIO_CHANNEL_RS485_DE));

    /* And it must end low, whatever the outcome of the exchange. */
    TEST_ASSERT_EQUAL_HEX8_MESSAGE(STD_LOW, Stub_Dio_GetLevel(DIO_CHANNEL_RS485_DE),
                                   "driver enable left asserted; the bus is now blocked");
}

/** @test TS-RS485-019 The request actually transmitted matches the reference frame. */
static void test_Exchange_TransmitsCorrectFrame(void)
{
    const uint8 *tx;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    STD_DISCARD(Rs485If_SwitchPacks(0x00u, 0x0Fu));

    TEST_ASSERT_EQUAL_UINT16(RS485IF_REQUEST_FRAME_SIZE_EXT, Stub_Uart_GetTxLength(RS485_BUS));
    tx = Stub_Uart_GetTxBuffer(RS485_BUS);
    TEST_ASSERT_NOT_NULL(tx);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(Rs485_Tv_RequestSwitchAll, tx, RS485IF_REQUEST_FRAME_SIZE_EXT);
}

/**
 * @test TS-RS485-020 Silence is counted as a timeout, a partial frame as a short frame.
 *
 * Distinguishing them is the difference between "the pack is absent or unpowered" and "the
 * pack is alive but the link is corrupting traffic", which lead to different repairs.
 */
static void test_Exchange_DistinguishesSilenceFromTruncation(void)
{
    Rs485If_StatisticsType stats;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    /* Nothing armed: the pack never answers at all. */
    TEST_ASSERT_EQUAL(E_TIMEOUT, Rs485If_SwitchPacks(0x00u, 0x00u));
    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(1u, stats.timeouts);
    TEST_ASSERT_EQUAL_UINT32(0u, stats.shortFrames);

    /* Now a reply that starts and then stops. It must be armed as a response to the
     * request rather than pre-queued, because the driver correctly purges anything already
     * buffered before it transmits. */
    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_RequestSwitchAll, 8u, TRUE);
    TEST_ASSERT_EQUAL(E_TIMEOUT, Rs485If_SwitchPacks(0x00u, 0x00u));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(1u, stats.timeouts);    /* unchanged: bytes did arrive */
    TEST_ASSERT_EQUAL_UINT32(1u, stats.shortFrames); /* incremented                */
}

/**
 * @test TS-RS485-021 A read timeout returns promptly instead of waiting out the deadline.
 *
 * v1's read loop had no early exit and always consumed its full 1000 ms. Three exchanges
 * per pack across four packs is twelve seconds inside a three second acquisition period,
 * which is why the v1 schedule permanently overran. The deadline here is derived from the
 * frame length and must be respected, not exceeded.
 */
static void test_Exchange_TimeoutIsBoundedByFrameLength(void)
{
    const uint32 expectedDeadline = RS485IF_RESPONSE_TIMEOUT_MS(RS485IF_REQUEST_FRAME_SIZE_EXT);
    uint32 elapsed;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    Stub_Gpt_SetMonotonicMs(0u);
    TEST_ASSERT_EQUAL(E_TIMEOUT, Rs485If_SwitchPacks(0x00u, 0x00u));
    elapsed = Gpt_ElapsedSince(0u);

    /* The 17-byte acknowledgement needs 17 * 11 / 4800 = 39 ms on the wire; the derived
     * deadline is that doubled plus the processing allowance, so well under v1's flat
     * second. */
    TEST_ASSERT_LESS_THAN_UINT32(500u, expectedDeadline);

    /* One attempt plus RS485IF_REQUEST_RETRIES retries, each bounded by the deadline, plus
     * the inter-request gaps. */
    TEST_ASSERT_LESS_OR_EQUAL_UINT32(
        ((expectedDeadline + RS485IF_INTER_REQUEST_GAP_MS) * (RS485IF_REQUEST_RETRIES + 2u)), elapsed);
}

/**
 * @test TS-RS485-022 A failed read clears the cached validity flag.
 *
 * Publishing a stale reading as current would make a dead pack look healthy, which is the
 * most misleading thing a battery monitor can do.
 */
static void test_ReadPackData_ClearsValidityOnFailure(void)
{
    Rs485If_PackStateType state;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    /* Not discovered, so not present: the read is refused without touching the bus. */
    TEST_ASSERT_EQUAL(E_NOT_FOUND, Rs485If_ReadPackData(1u));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetPackState(1u, &state));
    TEST_ASSERT_FALSE(state.present);
    TEST_ASSERT_FALSE(state.packDataValid);
    TEST_ASSERT_FALSE(state.cellDataValid);

    /* Out-of-range slots are rejected, not clamped. */
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ReadPackData(0u));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ReadPackData((Rs485If_SlotType)(RS485IF_PACK_COUNT + 1u)));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_GetPackState(0u, &state));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_GetPackState(1u, NULL_PTR));
}

/** @test TS-RS485-023 A valid acknowledgement completes a switch command. */
static void test_SwitchPacks_AcceptsValidAcknowledgement(void)
{
    Rs485If_StatisticsType stats;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_ResponseSwitchAck, RS485IF_REQUEST_FRAME_SIZE_EXT, TRUE);

    TEST_ASSERT_EQUAL(E_OK, Rs485If_SwitchPacks(0x00u, 0x0Fu));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_EQUAL_UINT32(1u, stats.framesSent);
    TEST_ASSERT_EQUAL_UINT32(1u, stats.framesReceived);
    TEST_ASSERT_EQUAL_UINT32(0u, stats.timeouts);
    TEST_ASSERT_EQUAL_UINT32(0u, stats.crcFailures);
}

/**
 * @test TS-RS485-024 Discovery learns a responding pack's serial number.
 *
 * The stub answers every request with the same serial-number frame, which is what a stuck
 * contactor looks like from the master's side: slot 1 is accepted, and slots 2 to 4 report
 * the identical serial and are rejected as duplicates. Accepting them would double-count
 * one physical pack's energy four times over in every aggregate the vehicle reports.
 */
static void test_DiscoverPacks_LearnsSerialAndRejectsDuplicates(void)
{
    Rs485If_PackStateType state;
    Rs485If_SlotType slot;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_ResponseSerial, RS485IF_SERIAL_RESPONSE_SIZE, TRUE);

    TEST_ASSERT_EQUAL(E_OK, Rs485If_DiscoverPacks());

    TEST_ASSERT_EQUAL_UINT8_MESSAGE(1u, Rs485If_GetPresentPackCount(),
                                    "duplicate serial numbers were accepted as distinct packs");

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetPackState(1u, &state));
    TEST_ASSERT_TRUE(state.present);
    TEST_ASSERT_EQUAL_HEX32(RS485_TV_SERIAL, state.serialNumber);

    for (slot = 2u; slot <= (Rs485If_SlotType)RS485IF_PACK_COUNT; slot++)
    {
        TEST_ASSERT_EQUAL(E_OK, Rs485If_GetPackState(slot, &state));
        TEST_ASSERT_FALSE(state.present);
        TEST_ASSERT_EQUAL_HEX32(0u, state.serialNumber);
    }
}

/** @test TS-RS485-025 A successful read populates the cache and marks it valid. */
static void test_ReadPackData_PopulatesCacheOnSuccess(void)
{
    Rs485If_PackStateType state;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_ResponseSerial, RS485IF_SERIAL_RESPONSE_SIZE, TRUE);
    TEST_ASSERT_EQUAL(E_OK, Rs485If_DiscoverPacks());

    /* The pack-parameter response echoes RS485_TV_SERIAL, which is what slot 1 learned, so
     * the echoed-serial check passes. */
    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_ResponseBatteryNominal, RS485IF_BATTERY_RESPONSE_SIZE, TRUE);

    TEST_ASSERT_EQUAL(E_OK, Rs485If_ReadPackData(1u));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetPackState(1u, &state));
    TEST_ASSERT_TRUE(state.packDataValid);
    TEST_ASSERT_EQUAL_UINT16(RS485_TV_NOM_VOLTAGE, state.pack.voltage);
    TEST_ASSERT_EQUAL_INT32(RS485_TV_NOM_CURRENT, state.pack.current);
    TEST_ASSERT_EQUAL_UINT8(RS485_TV_NOM_SOC, state.pack.stateOfCharge);
    TEST_ASSERT_EQUAL_UINT32(0u, state.consecutiveFailures);

    /* And the cell read, which shares the transport, still reports invalid until it runs. */
    TEST_ASSERT_FALSE(state.cellDataValid);
}

/**
 * @test TS-RS485-026 A reply echoing another pack's serial number is rejected.
 *
 * v1 validated only the CRC, so a perfectly formed reply from the wrong pack was accepted
 * and its measurements were logged against a different slot. On a shared half-duplex bus
 * that is a realistic outcome of a late reply or a stuck contactor.
 */
static void test_ReadPackData_RejectsReplyFromWrongPack(void)
{
    Rs485If_PackStateType state;
    Rs485If_StatisticsType stats;
    uint8 wrongPackFrame[RS485IF_BATTERY_RESPONSE_SIZE];
    uint16 crc;

    TEST_ASSERT_EQUAL(E_OK, Uart_Init());
    TEST_ASSERT_EQUAL(E_OK, Rs485If_Init());

    Stub_Uart_SetTxResponse(RS485_BUS, Rs485_Tv_ResponseSerial, RS485IF_SERIAL_RESPONSE_SIZE, TRUE);
    TEST_ASSERT_EQUAL(E_OK, Rs485If_DiscoverPacks());

    /* Take the valid frame and re-address it to a different pack, repairing the CRC so that
     * the *only* thing wrong is the identity. A validator checking the CRC alone accepts it. */
    (void)memcpy(wrongPackFrame, Rs485_Tv_ResponseBatteryNominal, sizeof(wrongPackFrame));
    wrongPackFrame[5] = 0x87u;
    wrongPackFrame[6] = 0x65u;
    wrongPackFrame[7] = 0x43u;
    wrongPackFrame[8] = 0x21u;
    crc = Crc_CalculateCRC16(wrongPackFrame, sizeof(wrongPackFrame) - 2u, 0u, TRUE);
    wrongPackFrame[sizeof(wrongPackFrame) - 2u] = (uint8)(crc >> 8u);
    wrongPackFrame[sizeof(wrongPackFrame) - 1u] = (uint8)(crc & 0xFFu);

    /* Confirm the frame really is well-formed apart from the identity. */
    TEST_ASSERT_EQUAL(E_OK, Rs485If_ValidateResponse(wrongPackFrame, (uint8)sizeof(wrongPackFrame),
                                                     RS485IF_BATTERY_RESPONSE_SIZE));

    Stub_Uart_SetTxResponse(RS485_BUS, wrongPackFrame, (uint16)sizeof(wrongPackFrame), TRUE);

    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ReadPackData(1u));

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetPackState(1u, &state));
    TEST_ASSERT_FALSE_MESSAGE(state.packDataValid, "another pack's reading was cached as this pack's");
    TEST_ASSERT_EQUAL_UINT32(1u, state.consecutiveFailures);

    TEST_ASSERT_EQUAL(E_OK, Rs485If_GetStatistics(&stats));
    TEST_ASSERT_GREATER_THAN_UINT32(0u, stats.serialMismatches);
}

/** @test TS-RS485-022b Calls before Init are rejected as uninitialised. */
static void test_Api_RejectsUseBeforeInit(void)
{
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_SwitchPacks(0u, 0u));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_DiscoverPacks());
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ReadPackData(1u));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_ReadCellData(1u));
    TEST_ASSERT_EQUAL(E_NOT_OK, Rs485If_PollAllPacks());
    TEST_ASSERT_EQUAL_UINT8(0u, Rs485If_GetPresentPackCount());
}

/*==================================================================================================
 *  Runner
 *================================================================================================*/

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_BuildRequest_MatchesReferenceFrame);
    RUN_TEST(test_BuildRequestExt_MatchesReferenceFrame);
    RUN_TEST(test_BuildRequest_DoesNotOverflowBuffer);
    RUN_TEST(test_BuildRequest_RejectsUndersizedBuffer);
    RUN_TEST(test_BuildRequest_RejectsNullBuffer);
    RUN_TEST(test_ValidateResponse_AcceptsGoldenFrames);
    RUN_TEST(test_ValidateResponse_RejectsV1CorruptFrame);
    RUN_TEST(test_ValidateResponse_DetectsEverySingleBitError);
    RUN_TEST(test_ValidateResponse_ClassifiesHeaderErrorsSeparately);
    RUN_TEST(test_ValidateResponse_RejectsWrongDeclaredLength);
    RUN_TEST(test_ValidateResponse_RejectsShortFrame);
    RUN_TEST(test_ParsePackData_DecodesNominalFrame);
    RUN_TEST(test_ParsePackData_DecodesNegativeFields);
    RUN_TEST(test_ParsePackData_DecodesExtremes);
    RUN_TEST(test_ParseCellData_DecodesAllChannels);
    RUN_TEST(test_ParseSerialNumber);
    RUN_TEST(test_Parsers_RejectNull);
    RUN_TEST(test_Exchange_PurgesStaleReceiveDataFirst);
    RUN_TEST(test_Exchange_TogglesDriverEnableAroundTransmit);
    RUN_TEST(test_Exchange_TransmitsCorrectFrame);
    RUN_TEST(test_Exchange_DistinguishesSilenceFromTruncation);
    RUN_TEST(test_Exchange_TimeoutIsBoundedByFrameLength);
    RUN_TEST(test_ReadPackData_ClearsValidityOnFailure);
    RUN_TEST(test_SwitchPacks_AcceptsValidAcknowledgement);
    RUN_TEST(test_DiscoverPacks_LearnsSerialAndRejectsDuplicates);
    RUN_TEST(test_ReadPackData_PopulatesCacheOnSuccess);
    RUN_TEST(test_ReadPackData_RejectsReplyFromWrongPack);
    RUN_TEST(test_Api_RejectsUseBeforeInit);
    return UNITY_END();
}
